tools/tizonia-travis-build-trusty: install libspotify

diff --git a/tools/tizonia-travis-build-trusty b/tools/tizonia-travis-build-trusty
--- a/tools/tizonia-travis-build-trusty
+++ b/tools/tizonia-travis-build-trusty
@@ -165,7 +165,7 @@ function start_dbus {
 #   None
 ##################################################################
 function install_deps {
-    echo "Installing debian dependencies..."
+    echo "Installing Tizonia's dependencies..."
     sudo apt-get update -qq \
         && sudo apt-get install -qq \
         build-essential \
@@ -218,7 +218,24 @@ function install_deps {
         sqlite3 \
         dbus-x11 \
         mercurial
-    return $?
+
+    exit_status=$?
+
+    if [[ "$exit_status" -ne 0 ]] ; then
+        echo "Error while installing gmusicapi" >&2
+    fi
+
+    echo "Installing libspotify..."
+    if [[ "$exit_status" -eq 0 ]] ; then
+        wget -q -O - http://apt.mopidy.com/mopidy.gpg | sudo apt-key add -
+        echo deb http://apt.mopidy.com/ stable main contrib non-free | sudo tee -a /etc/apt/sources.list
+        echo deb-src http://apt.mopidy.com/ stable main contrib non-free | sudo tee -a /etc/apt/sources.list
+        sudo apt-get update -qq \
+            && sudo apt-get install libspotify12 libspotify-dev -qq
+        exit_status=$?
+    fi
+
+    return $exit_status
 }
 
 ##################################################################
@@ -239,6 +256,8 @@ function install_python_deps {
     wget https://bootstrap.pypa.io/get-pip.py \
         && sudo python get-pip.py \
         && pip install --user gmusicapi
+
+    exit_status=$?
 
     # echo "Now installing the latest gmusicapi from source..."
     # git clone https://github.com/simon-weber/gmusicapi \
