tools/tizonia-dev-build: fixes + improvements

diff --git a/tools/tizonia-dev-build b/tools/tizonia-dev-build
--- a/tools/tizonia-dev-build
+++ b/tools/tizonia-dev-build
@@ -200,10 +200,38 @@ function exists_in_array {
 }
 
 function raise_error {
-    echo -e "\n[!!!] $@" 1>&2
+    pretty_print "$RED" "$@" 1>&2
     exit 1
 }
 
+function build_project {
+    local install_option=${1:-''}
+    local buildlog=$(mktemp)
+    local exit_status=0
+    local procs=$(nproc)
+    local jobcnt=$(( $procs + 1 ))
+    print_banner "Building Tizonia [$jobcnt jobs]" "$GRN"
+    if [[ -z "$install_option" ]]; then
+        make -s -j"$jobcnt" V=0 2>&1 | tee "$buildlog"
+    else
+        make -s -j"$jobcnt" V=0 2>&1 install | tee "$buildlog"
+    fi
+    exit_status="${PIPESTATUS[0]}"
+    if [[ "$exit_status" != 0 ]]; then
+        grep -q 'internal compiler error' "$buildlog"
+        if [[ "$?" -eq 0 ]]; then
+            print_banner "Building Tizonia [2nd pass, 1 job]" "$GRN"
+            if [[ -z "$install_option" ]]; then
+                make -s -j1 V=0
+            else
+                make -s -j1 V=0 install
+            fi
+            exit_status="$?"
+        fi
+    fi
+    rm -f "$buildlog"
+    return "$exit_status"
+}
 
 ##################################################################
 # Main function
@@ -279,6 +307,13 @@ function main {
         esac
     done
 
+    set -o nounset
+    set -o pipefail
+
+    if [[ ("$deps" == 1) ]]; then
+        tizonia-dpkg-build --tizdeps
+        exit $?
+    fi
 
     local make_install_total=$(( $make + $install ))
 
@@ -303,12 +338,10 @@ function main {
     PKG_CONFIG_DIR="$LIB_DIR"/pkgconfig
 
     print_banner "Exporting environment variables" "$GRN"
-    pretty_print "$BLU" "export LD_LIBRARY_PATH=$LIB_DIR"
-    pretty_print "$BLU" "export PKG_CONFIG_PATH=$PKG_CONFIG_DIR"
+    pretty_print "$BLU" "LD_LIBRARY_PATH=$LIB_DIR"
+    pretty_print "$BLU" "PKG_CONFIG_PATH=$PKG_CONFIG_DIR"
     export LD_LIBRARY_PATH="$LIB_DIR"
     export PKG_CONFIG_PATH="$PKG_CONFIG_DIR"
-
-    set -e
 
     local builddir="$TIZONIA_REPO_DIR"
     if [[ "$player" == 1 ]]; then
@@ -319,7 +352,8 @@ function main {
         builddir="$PWD"
     fi
 
-    print_banner "Changing dir to $builddir" "$GRN"
+    echo
+    pretty_print "$MAG" "Changing dir to $builddir"
     cd "$builddir"
 
     local config=1
@@ -332,21 +366,21 @@ function main {
         print_banner "Reconfiguring Tizonia for [DEBUG] build - Install dir [$TIZONIA_INSTALL_DIR]..." "$YEL"
         autoreconf -ifs \
             && ./configure \
-            --enable-silent-rules \
-            --prefix="$TIZONIA_INSTALL_DIR" \
-            CFLAGS='-O0 -ggdb -Wall -Werror' \
-            CXXFLAGS='-O0 -ggdb -Wall'
+                   --enable-silent-rules \
+                   --prefix="$TIZONIA_INSTALL_DIR" \
+                   CFLAGS='-O0 -ggdb -Wall -Werror' \
+                   CXXFLAGS='-O0 -ggdb -Wall'
 
     elif [[ ("$asan" == 1) ]]; then
 
         print_banner "Reconfiguring Tizonia for [ASAN] build - Install dir [$TIZONIA_INSTALL_DIR]..." "$YEL"
         autoreconf -ifs \
             && ./configure \
-            --enable-silent-rules \
-            --prefix="$TIZONIA_INSTALL_DIR" \
-            CFLAGS='-ggdb -Wall -Werror -fno-omit-frame-pointer -fsanitize=address' \
-            CXXFLAGS='-ggdb -Wall -fno-omit-frame-pointer -fsanitize=address' \
-            LDFLAGS='-fsanitize=address'
+                   --enable-silent-rules \
+                   --prefix="$TIZONIA_INSTALL_DIR" \
+                   CFLAGS='-ggdb -Wall -Werror -fno-omit-frame-pointer -fsanitize=address' \
+                   CXXFLAGS='-ggdb -Wall -fno-omit-frame-pointer -fsanitize=address' \
+                   LDFLAGS='-fsanitize=address'
 
     elif [[ ("$debian" == 1) ]]; then
 
@@ -365,38 +399,39 @@ function main {
 
         print_banner "Reconfiguring Tizonia for [RELEASE] build - Install dir [$TIZONIA_INSTALL_DIR]..." "$YEL"
         autoreconf -ifs \
-            && ./configure --enable-silent-rules \
-            --prefix="$TIZONIA_INSTALL_DIR" \
-            CFLAGS='-O2 -s -DNDEBUG'  \
-            CXXFLAGS='-O2 -s -DNDEBUG -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security'
+        && ./configure \
+               --enable-silent-rules \
+               --prefix="$TIZONIA_INSTALL_DIR" \
+               CFLAGS='-O2 -s -DNDEBUG'  \
+               CXXFLAGS='-O2 -s -DNDEBUG -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security'
 
     elif [[ ("$conf" == 1)  ]];  then
 
         print_banner "Reconfiguring Tizonia for [CONFORMANCE TESTING] build - Install dir [$TIZONIA_INSTALL_DIR]..." "$YEL"
         autoreconf -ifs \
             && ./configure \
-            --enable-silent-rules \
-            --enable-blocking-etb-ftb \
-            --prefix="$TIZONIA_INSTALL_DIR" \
-            CFLAGS='-ggdb -Wall -Werror'
+                   --enable-silent-rules \
+                   --enable-blocking-etb-ftb \
+                   --prefix="$TIZONIA_INSTALL_DIR" \
+                   CFLAGS='-ggdb -Wall -Werror'
 
     elif [[ ("$valgrind" == 1)  ]];  then
 
         print_banner "Reconfiguring Tizonia for [VALGRIND] build - Install dir [$TIZONIA_INSTALL_DIR]..." "$YEL"
         autoreconf -ifs \
-            && ./configure \
-            --enable-silent-rules \
-            --prefix="$TIZONIA_INSTALL_DIR" \
-            CFLAGS='-O0 -g' \
-            CXXFLAGS='-O0 -g'
+        && ./configure \
+               --enable-silent-rules \
+               --prefix="$TIZONIA_INSTALL_DIR" \
+               CFLAGS='-O0 -g' \
+               CXXFLAGS='-O0 -g'
 
     elif [[ ("$scan" == 1) ]]; then
 
         print_banner "Reconfiguring Tizonia for [SCAN-BUILD] build - Install dir [$TIZONIA_INSTALL_DIR]..." "$YEL"
         scan-build autoreconf -ifs \
             && scan-build ./configure \
-            --prefix="$TIZONIA_INSTALL_DIR" \
-            CFLAGS='-ggdb -Wall -Werror'
+                          --prefix="$TIZONIA_INSTALL_DIR" \
+                          CFLAGS='-ggdb -Wall -Werror'
 
     fi
 
@@ -411,17 +446,21 @@ function main {
         print_banner "Building for [VALGRIND] build" "$GRN"
         make CFLAGS='-O0 -g' CXXFLAGS='-O0 -g'
     elif [[ ("$make" == 1) || ("$install" == 1) ]]; then
-        print_banner "Building Tizonia" "$GRN"
-        make -s -j8 V=0
+        build_project
     fi
 
     if [[ "$?" != 0 ]]; then
-        raise_error "make install failure."
+        echo "raise error"
+        raise_error "*** make failed ***"
     fi
 
-    if [[ ("$install" == 1) ]]; then
-        print_banner "Installing Tizonia - Install dir [$TIZONIA_INSTALL_DIR]" "$GRN"
-        make -s -j8 V=0 install
+    if [[ "$install" == 1 ]]; then
+        build_project "install"
+    fi
+
+    if [[ "$?" != 0 ]]; then
+        echo "raise error"
+        raise_error "*** make install failed ***"
     fi
 
     exit "$?"
