tizonia-snap-wrapper.sh: allow armhf and i386

diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -45,12 +45,17 @@ parts:
     source: https://github.com/tizonia/tizonia-openmax-il.git
     # source-tag: 0.7.0
     prepare: |
+      # NOTE: The check for Mopidy's apt archive presence in sources.list is disabled,
+      # since it fails when building with 'snapcraft cleanbuild'.
+      # Re-enable when building without cleanbuild to avoid adding the apt archive
+      # multiple times to sources.list.
+      #
       # Add Mopidy's archive to APT's sources.list
-      grep -q "apt.mopidy.com" /etc/apt/sources.list
-      if [ "$?" -eq 1 ]; then
-          curl 'http://apt.mopidy.com/mopidy.gpg' | sudo apt-key add -
-          echo "deb http://apt.mopidy.com/ stable main contrib non-free" | sudo tee -a /etc/apt/sources.list
-      fi
+      # grep -q "apt.mopidy.com" /etc/apt/sources.list
+      # if [ "$?" -eq 1 ]; then
+      curl 'http://apt.mopidy.com/mopidy.gpg' | sudo apt-key add -
+      echo "deb http://apt.mopidy.com/ stable main contrib non-free" | sudo tee -a /etc/apt/sources.list
+      # fi
       sudo apt-get update && sudo apt-get -y install libspotify-dev
     build: |
       autoreconf -ifsv 2>&1 | grep --color=always '.*Entering directory' && ./configure --prefix=$SNAPCRAFT_PART_INSTALL --without-bashcompletiondir --without-zshcompletiondir --enable-silent-rules CFLAGS='-O2 -s -DNDEBUG' CXXFLAGS='-O2 -s -DNDEBUG -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' | grep --color=always '=== configuring in' && make -j1 V=0
